name: Glacier
options:
  bundleIdPrefix: com.fran
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38.0"
targets:
  Glacier:
    type: application
    platform: macOS
    sources: [Glacier]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.glacier.app
        INFOPLIST_FILE: Glacier/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Glacier.entitlements
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: Glacier
        MARKETING_VERSION: "0.1.0"
